name: CI for sample-container-todo-app-java-maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw clean install
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-result-junit
          path: target/surefire-reports/
