name: CI for sample-container-todo-app-java-maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: build
  release:
    uses: ./.github/workflows/release.yml
    needs: test
