name: Get Job Id
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    outputs:
      # This is useful to propagate job ID to other jobs with "needs".
      run_id: ${{ steps.get-job-id.outputs.result }}
    steps:
      - name: Dump github context
        run: echo '${{ toJSON(github) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'        
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump step context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: "Get this job's run ID"
        id: get-job-id
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            //console.log(result);
            const currentJobs = result.data.jobs.
              filter(it => it.status === 'in_progress' && it.runner_name === process.env.RUNNER_NAME);
            const currentJobId = currentJobs[0].id;
            console.log("Current job id:", currentJobId);
            return currentJobId;
      - name: "My job ID is ${{steps.get-job-id.outputs.result}}"
        run: >
          echo "get-job-id=${{steps.get-job-id.outputs.result}}"
      - name: "Runner name"
        id: runner-name
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.RUNNER_NAME)

  use-other-job-id:
    name: Use other job
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: "Get this job's run ID"
        id: get-job-id
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            //console.log(result);
            const currentJobs = result.data.jobs.
              filter(it => it.status === 'in_progress' && it.runner_name === process.env.RUNNER_NAME);
            const currentJobId = currentJobs[0].id;
            console.log("Current job id:", currentJobId);
            return currentJobId;
      - name: "My job ID is ${{steps.get-job-id.outputs.result}}"
        run: >
          echo "get-job-id=${{steps.get-job-id.outputs.result}}"
      - name: "Runner name"
        id: runner-name
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.RUNNER_NAME)
            
  use-another-job-id:
    name: Use another job
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: "Get this job's run ID"
        id: get-job-id
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            //console.log(result);
            const currentJobs = result.data.jobs.
              filter(it => it.status === 'in_progress' && it.runner_name === process.env.RUNNER_NAME);
            const currentJobId = currentJobs[0].id;
            console.log("Current job id:", currentJobId);
            return currentJobId;
      - name: "My job ID is ${{steps.get-job-id.outputs.result}}"
        run: >
          echo "get-job-id=${{steps.get-job-id.outputs.result}}"
      - name: "Runner name"
        id: runner-name
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.RUNNER_NAME)            
