name: Release sample-container-todo-app-java-maven to Docker Hub

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  release:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: tolgatakir/sample-container-todo-app-java-maven
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'maven'
      - name: Collect Workflow Telemetry
        uses: thundra-io/workflow-telemetry-action@v1
      - name: Create Artifact
        run: ./mvnw -B clean package -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker Image
        run: docker push $REPO -a
      - name: "Get this job's run ID"
        id: get-job-id
        uses: actions/github-script@v6
        with:
          script: |
            const getJobId = async() => {
              const result = await github.rest.actions.listJobsForWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId,
                per_page: 100,
              });
              const currentJobs = result.data.jobs.
                filter(it => it.status === 'in_progress' && it.runner_name === process.env.RUNNER_NAME);
              if (currentJobs && currentJobs.length) {
                return currentJobs[0].id;
              }
              return null;
            }
            for (let i = 0; i < 10; i++) {
              const currentJobId = await getJobId();
              if (currentJobId) {
                console.log("Current job id:", currentJobId);
                return currentJobId;
              }
              await new Promise(r => setTimeout(r, 1000));
            }
      - name: "My job ID is ${{steps.get-job-id.outputs.result}}"
        run: >
          echo "get-job-id=${{steps.get-job-id.outputs.result}}"
      - name: "Runner name"
        id: runner-name
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.RUNNER_NAME)
