name: Test for sample-container-todo-app-java-maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 8, 11, 16 ]
    name: Run Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Run Tests with Maven
        run: ./mvnw clean test
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-result-junit
          path: target/surefire-reports/
